[project]
name = "payment-processing-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mudra111", email = "mudrabhalodiya@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
]

[project.scripts]
payment-processing-system = "payment_processing_system:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
